In [1]:
%%bash
python3 -m pip install nashpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.7/29.7 MB 11.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 12.5 MB/s eta 0:00:00
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)


In [9]:
import nashpy as nash
import numpy as np

In [10]:
U_1 = np.array([[4, 1], [6, 2]])
U_2 = np.array([[4, 6], [1, 2]])
game = nash.Game(U_1, U_2)
game
# Bi matrix game with payoff matrices:

# Row player:
# [[4 1]
#  [6 2]]

# Column player:
# [[4 6]
#  [1 2]]

Bi matrix game with payoff matrices:

Row player:
[[4 1]
 [6 2]]

Column player:
[[4 6]
 [1 2]]

In [15]:
equilibria = game.support_enumeration()
list(equilibria)  # [(array([0., 1.]), array([0., 1.]))]

[(array([0., 1.]), array([0., 1.]))]