In [2]:
%%bash
python3 -m pip install nashpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.6 MB/s eta 0:00:00
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 15.1 MB/s eta 0:00:0000:0100:01


In [3]:
import nashpy as nash
import numpy as np

In [4]:
U_1 = np.array([[4, 1], [6, 2]])
U_2 = np.array([[4, 6], [1, 2]])
game = nash.Game(U_1, U_2)
game
# Bi matrix game with payoff matrices:

# Row player:
# [[4 1]
#  [6 2]]

# Column player:
# [[4 6]
#  [1 2]]

Bi matrix game with payoff matrices:

Row player:
[[4 1]
 [6 2]]

Column player:
[[4 6]
 [1 2]]

In [5]:
equilibria = game.support_enumeration()
list(equilibria)  # [(array([0., 1.]), array([0., 1.]))]

[(array([0., 1.]), array([0., 1.]))]

In [6]:
A = np.array([[1, -1], [-1, 1]])
matching_pennies = nash.Game(A)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [12]:
A = np.array([[3, 0], [5, 1]])
B = np.array([[3, 5], [0, 1]])
prisoners_dilemma = nash.Game(A, B)
print(prisoners_dilemma)

# The utility for both players when they both play their first action:
sigma_r1 = np.array([1, 0])
sigma_c1 = np.array([1, 0])
print("Both cooperate: " + str(prisoners_dilemma[sigma_r1, sigma_c1]))

# The utility to both players when they play uniformly randomly across both their actions:
sigma_r2 = np.array([1 / 2, 1 / 2])
sigma_c2 = np.array([1 / 2, 1 / 2])
print("Mixed strategy: " + str(prisoners_dilemma[sigma_r2, sigma_c2]))

Bi matrix game with payoff matrices:

Row player:
[[3 0]
 [5 1]]

Column player:
[[3 5]
 [0 1]]
Both cooperate: [3 3]
Mixed strategy: [2.25 2.25]
